dress/core/urls.py
from django.conf.urls import include, url
from dress.core import views as c
from dress.core import graphics as g

customers_patterns = [
    url(r'^$', c.CustomerList.as_view(), name='customer_list'),
    url(r'^add/$', c.customer_create, name='customer_add'),
    url(r'^(?P<pk>\d+)/$', c.customer_detail, name='customer_detail'),
    url(r'^(?P<pk>\d+)/edit/$', c.customer_update, name='customer_edit'),
    url(r'^(?P<pk>\d+)/delete/$', c.customer_delete, name='customer_delete'),
    url(r'^customer_per_size_json/$', g.customer_per_size_json),
]

dresses_patterns = [
    url(r'^$', c.DressList.as_view(), name='dress_list'),
    url(r'^add/$', c.dress_create, name='dress_add'),
    url(r'^(?P<pk>\d+)/$', c.dress_detail, name='dress_detail'),
    url(r'^(?P<pk>\d+)/edit/$', c.dress_update, name='dress_edit'),
    url(r'^(?P<pk>\d+)/delete/$', c.dress_delete, name='dress_delete'),
    url(r'^dress_per_color_json/$', g.dress_per_color_json),
    url(r'^dress_per_size_json/$', g.dress_per_size_json),
]

orders_patterns = [
    url(r'^$', c.OrderList.as_view(), name='order_list'),
    url(r'^add/$', c.order_create, name='order_add'),
    url(r'^(?P<pk>\d+)/$', c.order_detail, name='order_detail'),
    url(r'^(?P<pk>\d+)/edit/$', c.order_update, name='order_edit'),
    url(r'^(?P<pk>\d+)/delete/$', c.order_delete, name='order_delete'),
    url(r'^order_per_day_json/$', g.order_per_day_json),
    url(r'^order_value_json/$', g.order_value_json),
]

urlpatterns = [
    url(r'^$', c.home, name='home'),
    url(r'^customers/', include(customers_patterns)),
    url(r'^dresses/', include(dresses_patterns)),
    url(r'^orders/', include(orders_patterns)),
]

dress/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from rest_framework import routers
from .core import views

router = routers.DefaultRouter()
router.register(r'customers', views.CustomerViewSet)
router.register(r'dresses', views.DressViewSet)
router.register(r'orders', views.OrderViewSet)

urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'', include('dress.core.urls', namespace='core')),
    url(r'^admin/', admin.site.urls),
]

dress/core/models.py
from django.db import models
from django.shortcuts import resolve_url as r
from localflavor.br.br_states import STATE_CHOICES
from dress.utils.lists import COLORS


class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em', auto_now_add=True, auto_now=False)
    modified = models.DateTimeField(
        'modificado em', auto_now_add=False, auto_now=True)

    class Meta:
        abstract = True


class Address(models.Model):
    address = models.CharField(
        u'endereço', max_length=100, null=True, blank=True)
    complement = models.CharField(
        'complemento', max_length=100, null=True, blank=True)
    district = models.CharField(
        'bairro', max_length=100, null=True, blank=True)
    city = models.CharField('cidade', max_length=100, null=True, blank=True)
    uf = models.CharField(
        'UF', max_length=2, choices=STATE_CHOICES, null=True, blank=True)
    cep = models.CharField('CEP', max_length=9, null=True, blank=True)

    class Meta:
        abstract = True


class Customer(TimeStampedModel, Address):
    first_name = models.CharField('nome', max_length=50)
    last_name = models.CharField(
        'sobrenome', max_length=50, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    phone = models.CharField('telefone', max_length=20)
    person_height = models.DecimalField(
        'altura', max_digits=3, decimal_places=2)
    bust = models.PositiveIntegerField('busto')
    hip = models.PositiveIntegerField('quadril')
    waist = models.PositiveIntegerField('cintura')
    heel = models.PositiveIntegerField('salto')
    person_size = models.PositiveIntegerField('tamanho')

    class Meta:
        ordering = ['first_name']
        verbose_name = 'cliente'
        verbose_name_plural = 'clientes'

    def __str__(self):
        return ' '.join(filter(None, [self.first_name, self.last_name]))

    full_name = property(__str__)

    def get_absolute_url(self):
        return r('core:customer_detail', pk=self.pk)


class Dress(TimeStampedModel):
    dress_model = models.CharField('modelo', max_length=50)
    stylist = models.CharField('estilista', max_length=50)
    color = models.CharField('cor', max_length=20, choices=COLORS)
    dress_height = models.DecimalField(
        'altura', max_digits=3, decimal_places=2)
    dress_size = models.PositiveIntegerField('tamanho')

    class Meta:
        ordering = ['dress_model']
        verbose_name = 'vestido'
        verbose_name_plural = 'vestidos'

    def __str__(self):
        return self.dress_model

    def get_absolute_url(self):
        return r('core:dress_detail', pk=self.pk)


class Order(TimeStampedModel):
    customer = models.ForeignKey('Customer', verbose_name='cliente')
    dress = models.ForeignKey('Dress', verbose_name='vestido')
    price = models.DecimalField('Aluguel', max_digits=6, decimal_places=2)

    class Meta:
        ordering = ['-created']
        verbose_name = 'pedido'
        verbose_name_plural = 'pedidos'

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return r('core:order_detail', pk=self.pk)

dress/core/forms.py
from django import forms
from .models import Customer, Dress, Order


class CustomerForm(forms.ModelForm):

    class Meta:
        model = Customer
        fields = ['first_name', 'last_name', 'email', 'phone',
                  'address', 'complement', 'district', 'city', 'uf', 'cep',
                  'person_height', 'bust', 'hip', 'waist', 'heel', 'person_size']


class DressForm(forms.ModelForm):

    class Meta:
        model = Dress
        fields = ['dress_model', 'stylist',
                  'color', 'dress_height', 'dress_size']


class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ['customer', 'dress', 'price']

dress/core/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy as r
from django.views.generic import CreateView, ListView, DetailView
from django.views.generic import UpdateView, DeleteView
from rest_framework import viewsets
from .mixins import NameSearchMixin, DressSearchMixin, OrderSearchMixin
from .models import Customer, Dress, Order
from .forms import CustomerForm, DressForm, OrderForm
from .serializers import CustomerSerializer, DressSerializer, OrderSerializer


def home(request):
    return render(request, 'index.html')


class CustomerList(NameSearchMixin, ListView):
    model = Customer
    paginate_by = 5


customer_detail = DetailView.as_view(model=Customer)

customer_create = CreateView.as_view(model=Customer, form_class=CustomerForm)

customer_update = UpdateView.as_view(model=Customer, form_class=CustomerForm)

customer_delete = DeleteView.as_view(
    model=Customer, success_url=r('core:customer_list'))


class DressList(DressSearchMixin, ListView):
    model = Dress
    paginate_by = 5


dress_detail = DetailView.as_view(model=Dress)

dress_create = CreateView.as_view(model=Dress, form_class=DressForm)

dress_update = UpdateView.as_view(model=Dress, form_class=DressForm)

dress_delete = DeleteView.as_view(
    model=Dress, success_url=r('core:dress_list'))


class OrderList(OrderSearchMixin, ListView):
    model = Order
    paginate_by = 10


order_detail = DetailView.as_view(model=Order)

order_create = CreateView.as_view(model=Order, form_class=OrderForm)

order_update = UpdateView.as_view(model=Order, form_class=OrderForm)

order_delete = DeleteView.as_view(
    model=Order, success_url=r('core:order_list'))


class CustomerViewSet(viewsets.ModelViewSet):
    ''' API endpoint that allows customers to be viewed or edited. '''
    queryset = Customer.objects.all().order_by('first_name')
    serializer_class = CustomerSerializer
    authentication_classes = []
    permission_classes = []


class DressViewSet(viewsets.ModelViewSet):
    ''' API endpoint that allows dress to be viewed or edited. '''
    queryset = Dress.objects.all().order_by('dress_model')
    serializer_class = DressSerializer
    authentication_classes = []
    permission_classes = []


class OrderViewSet(viewsets.ModelViewSet):
    ''' API endpoint that allows orders to be viewed or edited. '''
    queryset = Order.objects.all().order_by('-created')
    serializer_class = OrderSerializer
    authentication_classes = []
    permission_classes = []

dress/core/templates/core/customer_detail.html
{% extends "base.html" %}

{% load static %}

{% block title %}Customer Detail{% endblock title %}

{% block content %}

<ul class="breadcrumb">
  <li><a href="{% url 'core:home' %}">Home</a> <span class="divider"></span></li>
  <li><a href="{% url 'core:customer_list' %}">Clientes</a> <span class="divider"></span></li>
  <li class="active">{{ object.full_name }}</li>
</ul>

<div class="col-lg-8">
  <div class="col-md-2 column">
    <img src="https://cdn3.iconfinder.com/data/icons/user-avatars-1/512/users-3-128.png" class="img-square" style="height: 100px;" />
  </div>
  <div class="col-md-offset-3 column">
    <h1>{{ object.full_name }}</h1>
    {% if object.email %}
      <h4><span class="glyphicon glyphicon-envelope"></span><a href="#"> {{ object.email }}</a></h4>
    {% endif %}
    <div class="social">
      <ul>
        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
        <li><a href="#"><i class="fa fa-instagram"></i></a></li>
      </ul>
    </div>
  </div>

  </br>

  <table class="table table-user-information">
    <tbody>
          <tr>
            <th class="col-md-3 text-right"><span class="glyphicon glyphicon-earphone"></span></th>
            <td>{{ object.phone }}</td>
          </tr>

      {% if object.address %}
        <tr>
          <th class="col-md-3 text-right"><span class="glyphicon glyphicon-map-marker"></span></th>
          <td>{{ object.address }}
            {% if object.complement %} - {{ object.complement }}{% endif %}
            {% if object.district %} - {{ object.district }}{% endif %}
          </td>
        </tr>
        <tr>
          <th class="col-md-3 text-right"></th>
          <td>
            {% if object.city %}{{ object.city }}{% endif %}
            {% if object.uf %} - {{ object.uf }}{% endif %}
            {% if object.cep %} - {{ object.cep }}{% endif %}
          </td>
        </tr>
      {% endif %}

      <tr>
        <th class="col-md-3 text-right">Altura</th>
          <td>{{ object.person_height }}</td>
      </tr>
      <tr>
        <th class="col-md-3 text-right">Busto</th>
          <td>{{ object.bust }}</td>
      </tr>
      <tr>
        <th class="col-md-3 text-right">Quadril</th>
          <td>{{ object.hip }}</td>
      </tr>
      <tr>
        <th class="col-md-3 text-right">Cintura</th>
          <td>{{ object.waist }}</td>
      </tr>
      <tr>
        <th class="col-md-3 text-right">Salto</th>
          <td>{{ object.heel }}</td>
      </tr>
      <tr>
        <th class="col-md-3 text-right">Tamanho</th>
          <td>{{ object.person_size }}</td>
      </tr>

    </tbody>
  </table>
  <!-- edit -->
  <a href="{% url 'core:customer_edit' customer.pk %}">
      <button id="edit_customer" type="button" class="btn btn-success">
          <span class="fa fa-pencil"></span> Editar
      </button>
  </a>
  <!-- delete with modal -->
  <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal">
      <span class="fa fa-times"></span> Excluir
  </button>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Confirmar</h4>
      </div>
        <form action="{% url 'core:customer_delete' customer.id %}" method="POST">
      <div class="modal-body">
          {% csrf_token %}
          Deseja mesmo deletar "{{ object }}"?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <input type="submit" class="btn btn-danger" value="Deletar" />
      </div>
        </form>
    </div>
  </div>
</div>


{% endblock content %}

dress/core/templates/core/customer_form.html
{% extends "base.html" %}

{% load bootstrap %}

{% block title %}Customer Form{% endblock title %}

{% block content %}

<form class="form-horizontal col-sm-6" action="." method="POST">
    <legend>Novo Cliente</legend>
    {% csrf_token %}
    {{ form|bootstrap_horizontal }}

    <div class="form-group">
      <div class="col-sm-2 col-sm-offset-2">
        <button type="submit" class="btn btn-primary">Salvar</button>
      </div>
    </div>
</form>

{% endblock content %}

dress/core/templates/core/customer_list.html
{% extends 'base.html' %}

{% block title %}Clientes{% endblock title %}

{% block content %}

<form class="navbar-form navbar-right" action="." method="get">
    <!-- add -->
    <a href="{% url 'core:customer_add' %}">
        <button id="new" type="button" class="btn btn-primary">
            <span class="glyphicon glyphicon-plus"></span> Adicionar
        </button>
    </a>
    <!-- search form -->
    <div class="form-group">
      <input id="search_box" name="search_box" type="text" placeholder="Localizar..." class="form-control">
      <button type="submit" class="btn btn-success form-control"><span class="glyphicon glyphicon-search"></span></button>
  </div>
</form>

<div class="page-header">
<h2>  Lista de Clientes</h2>
</div>

<div>
{% if customer_list %}
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Email</th>
        <th>Telefone</th>
        <th>Cidade</th>
        <th>UF</th>
        <th>Altura</th>
        <th>Tamanho</th>
      </tr>
    </thead>
    <tbody>
    {% for customer in customer_list %}
      <tr>
        <td><a href="{{ customer.get_absolute_url }}">{{ customer.full_name }}</a></td>
        <td>{{ customer.email }}</td>
        <td>{{ customer.phone }}</td>
        <td>{{ customer.city }}</td>
        <td>{{ customer.get_uf_display }}</td>
        <td>{{ customer.person_height }}</td>
        <td>{{ customer.person_size }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% else %}
  <p class="alert alert-warning">Sem itens na lista.</p>
{% endif %}
</div>

<hr>
<div>
<h4><b>Total:</b> {{ page_obj.paginator.count }} cliente{{ page_obj.paginator.count|pluralize }}</h4>
</div>

{% include "pagination.html" %}

{% endblock content %}

dress/core/templates/core/dress_detail.html
{% extends "base.html" %}

{% load static %}

{% block title %}Dress Detail{% endblock title %}

{% block content %}

<ul class="breadcrumb">
  <li><a href="{% url 'core:home' %}">Home</a> <span class="divider"></span></li>
  <li><a href="{% url 'core:dress_list' %}">Vestidos</a> <span class="divider"></span></li>
  <li class="active">{{ object.dress_model }}</li>
</ul>

<div class="col-lg-8">
  <div class="col-md-2 column">
    <img src="https://cdn2.iconfinder.com/data/icons/clothing-and-accessories-1/80/clothing_accesories_clothes_fabric-05-128.png" class="img-square" style="height: 100px;" />
  </div>
  <div class="col-md-offset-3 column">
    <h1>{{ object.dress_model }}</h1>
    <h4>{{ object.stylist }}</h4>
  </div>

  </br>

  <table class="table table-user-information">
    <tbody>
      <tr>
        <th class="col-md-3 text-right">Cor</th>
        <td>{{ object.get_color_display }}</td>
      </tr>
      <tr>
        <th class="col-md-3 text-right">Altura</th>
          <td>{{ object.dress_height }}</td>
      </tr>
      <tr>
        <th class="col-md-3 text-right">Tamanho</th>
          <td>{{ object.dress_size }}</td>
      </tr>

    </tbody>
  </table>
  <!-- edit -->
  <a href="{% url 'core:dress_edit' dress.pk %}">
      <button id="edit_dress" type="button" class="btn btn-success">
          <span class="fa fa-pencil"></span> Editar
      </button>
  </a>
  <!-- delete with modal -->
  <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal">
      <span class="fa fa-times"></span> Excluir
  </button>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Confirmar</h4>
      </div>
        <form action="{% url 'core:dress_delete' dress.id %}" method="POST">
      <div class="modal-body">
          {% csrf_token %}
          Deseja mesmo deletar "{{ object }}"?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <input type="submit" class="btn btn-danger" value="Deletar" />
      </div>
        </form>
    </div>
  </div>
</div>


{% endblock content %}

dress/core/templates/core/dress_form.html
{% extends "base.html" %}

{% load bootstrap %}

{% block title %}Dress Form{% endblock title %}

{% block content %}

<form class="form-horizontal col-sm-6" action="." method="POST">
    <legend>Novo Vestido</legend>
    {% csrf_token %}
    {{ form|bootstrap_horizontal }}

    <div class="form-group">
      <div class="col-sm-2 col-sm-offset-2">
        <button type="submit" class="btn btn-primary">Salvar</button>
      </div>
    </div>
</form>

{% endblock content %}

dress/core/templates/core/dress_list.html
{% extends 'base.html' %}

{% block title %}Vestidos{% endblock title %}

{% block content %}

<form class="navbar-form navbar-right" action="." method="get">
    <!-- add -->
    <a href="{% url 'core:dress_add' %}">
        <button id="new" type="button" class="btn btn-primary">
            <span class="glyphicon glyphicon-plus"></span> Adicionar
        </button>
    </a>
    <!-- search form -->
    <div class="form-group">
      <input id="search_box" name="search_box" type="text" placeholder="Localizar..." class="form-control">
      <button type="submit" class="btn btn-success form-control"><span class="glyphicon glyphicon-search"></span></button>
  </div>
</form>

<div class="page-header">
<h2>Lista de Vestidos</h2>
</div>

<div>
{% if dress_list %}
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Modelo</th>
        <th>Estilista</th>
        <th>Cor</th>
        <th>Altura</th>
        <th>Tamanho</th>
      </tr>
    </thead>
    <tbody>
    {% for dress in dress_list %}
      <tr>
        <td><a href="{{ dress.get_absolute_url }}">{{ dress.dress_model }}</a></td>
        <td>{{ dress.stylist }}</td>
        <td>{{ dress.color }}</td>
        <td>{{ dress.dress_height }}</td>
        <td>{{ dress.dress_size }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% else %}
  <p class="alert alert-warning">Sem itens na lista.</p>
{% endif %}
</div>

<hr>
<div>
<h4><b>Total:</b> {{ page_obj.paginator.count }} vestido{{ page_obj.paginator.count|pluralize }}</h4>
</div>

{% include "pagination.html" %}

{% endblock content %}

dress/core/templates/core/order_detail.html
{% extends "base.html" %}

{% load static %}

{% block title %}Order Detail{% endblock title %}

{% block content %}

<ul class="breadcrumb">
  <li><a href="{% url 'core:home' %}">Home</a> <span class="divider"></span></li>
  <li><a href="{% url 'core:order_list' %}">Pedidos</a> <span class="divider"></span></li>
  <li class="active">{{ object.id }}</li>
</ul>

<div class="col-lg-8">

  <table class="table table-user-information">
    <tbody>
      <tr>
        <th class="col-md-3 text-right">Pedido</th>
        <td>{{ object.id }}</td>
      </tr>
      <tr>
        <th class="col-md-3 text-right">Data</th>
        <td>{{ object.created }}</td>
      </tr>
      <tr>
        <th class="col-md-3 text-right">Cliente</th>
        <td>{{ object.customer }}</td>
      </tr>
      <tr>
        <th class="col-md-3 text-right">Vestido</th>
          <td>{{ object.dress }}</td>
      </tr>
      <tr>
        <th class="col-md-3 text-right">Aluguel</th>
          <td>{{ object.price }}</td>
      </tr>

    </tbody>
  </table>
  <!-- edit -->
  <a href="{% url 'core:order_edit' order.pk %}">
      <button id="edit_order" type="button" class="btn btn-success">
          <span class="fa fa-pencil"></span> Editar
      </button>
  </a>
  <!-- delete with modal -->
  <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal">
      <span class="fa fa-times"></span> Excluir
  </button>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Confirmar</h4>
      </div>
        <form action="{% url 'core:order_delete' order.id %}" method="POST">
      <div class="modal-body">
          {% csrf_token %}
          Deseja mesmo deletar "{{ object }}"?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <input type="submit" class="btn btn-danger" value="Deletar" />
      </div>
        </form>
    </div>
  </div>
</div>


{% endblock content %}

dress/core/templates/core/order_list.html
{% extends 'base.html' %}

{% block title %}Pedidos{% endblock title %}

{% block content %}

<form class="navbar-form navbar-right" action="." method="get">
    <!-- add -->
    <a href="{% url 'core:order_add' %}">
        <button id="new" type="button" class="btn btn-primary">
            <span class="glyphicon glyphicon-plus"></span> Adicionar
        </button>
    </a>
    <!-- search form -->
    <div class="form-group">
      <input id="search_box" name="search_box" type="text" placeholder="Localizar..." class="form-control">
      <button type="submit" class="btn btn-success form-control"><span class="glyphicon glyphicon-search"></span></button>
  </div>
</form>

<div class="page-header">
<h2>Lista de Pedidos</h2>
</div>

<div>
{% if order_list %}
  <table class="table table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th>Cliente</th>
        <th>Vestido</th>
        <th class="text-right">Aluguel</th>
      </tr>
    </thead>
    <tbody>
    {% for order in order_list %}
      <tr>
        <td><a href="{{ order.get_absolute_url }}">{{ order.id }}</a></td>
        <td>{{ order.customer }}</td>
        <td>{{ order.dress }}</td>
        <td class="text-right">R$ {{ order.price }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% else %}
  <p class="alert alert-warning">Sem itens na lista.</p>
{% endif %}
</div>

<hr>
<div>
<h4><b>Total:</b> {{ page_obj.paginator.count }} pedido{{ page_obj.paginator.count|pluralize }}</h4>
</div>

{% include "pagination.html" %}

{% endblock content %}

dress/core/templates/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}
  <div class="jumbotron">
    <a href="{% url 'core:customer_add' %}">
      <button id="new_customer" type="button" class="btn btn-primary">
        <span class="glyphicon glyphicon-plus"></span> Cadastre-se
      </button>
    </a>
    <a href="{% url 'core:order_add' %}">
      <button id="new_order" type="button" class="btn btn-info">
        <span class="glyphicon glyphicon-plus"></span> Faça seu pedido
      </button>
    </a>
    Veja os 5 gráficos abaixo.
  </div>

  <div>
    <div class="col-lg-6">
      <div class="panel panel-default">
        <div class="panel-heading lead">
          Quantidade de clientes por tamanho
        </div>
        <div class="panel-body">
          <div id="person_size_chart" class="graph"></div>
       </div>
      </div>
    </div>
  </div>

  <div>
    <div class="col-lg-6">
      <div class="panel panel-default">
        <div class="panel-heading lead">
          Quantidade de vestidos por tamanho
        </div>
        <div class="panel-body">
          <div id="dress_size_chart" class="graph"></div>
       </div>
      </div>
    </div>
  </div>

  <div>
    <div class="col-lg-6">
      <div class="panel panel-default">
        <div class="panel-heading lead">
          Quantidade de vestidos por cor
        </div>
        <div class="panel-body">
          <div id="dress_color_chart" class="graph"></div>
       </div>
      </div>
    </div>
  </div>

  <div>
    <div class="col-lg-6">
      <div class="panel panel-default">
        <div class="panel-heading lead">
          Quantidade de pedidos por dia
        </div>
        <div class="panel-body">
          <div id="order_per_day_chart" class="graph"></div>
       </div>
      </div>
    </div>
  </div>

  <div>
    <div>
      <div class="panel panel-default">
        <div class="panel-heading lead">
          Valor de cada pedido
        </div>
        <div class="panel-body">
          <div id="order_value_chart" class="graph"></div>
       </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block js %}
  <script src="{% static 'js/graphics/person_size_chart.js' %}"></script>
  <script src="{% static 'js/graphics/dress_size_chart.js' %}"></script>
  <script src="{% static 'js/graphics/dress_color_chart.js' %}"></script>
  <script src="{% static 'js/graphics/order_per_day_chart.js' %}"></script>
  <script src="{% static 'js/graphics/order_value_chart.js' %}"></script>
{% endblock js %}

dress/core/templates/nav.html
<!-- Menu -->
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="current"><a href="{% url 'core:home' %}"><span class="glyphicon glyphicon-home"></span> Home</a></li>
        <li><a href="{% url 'core:customer_list' %}">Clientes</a></li>
        <li><a href="{% url 'core:dress_list' %}">Vestidos</a></li>
        <li><a href="{% url 'core:order_list' %}">Pedidos</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'admin:index' %}"><span class="fa fa-drupal"></span> Admin</a></li>
      </ul>
    </div>
  </div>
</div>